### PR TITLE
feat: improve the Project flow in cli

### PR DESCRIPTION
**Pull request by amands98**
- [x] List
image

- [x] Delete

image

- [x] Create

image

- [ ] View

In the view where we display project information, we will also list the scanners and repositories associated with that project.

### CODE REVIEW

**Comment by amands98** [comment]
@Vad1mo

**Review by Vad1mo — COMMENTED** [review]
keep in mind that the harbor CLIs should also be usable in non-interactive mode, In CI/CD pipelines, in scripts. piping in yaml/json and outputting jsons/yaml are equally important.

**Comment by amands98** [comment]
Test Case : 

- [ ] Project
- [ ] Registry

**Comment by amands98** [comment]
We handle projects in this PR only. Will open a separate one for the registry. I've also added subcommands `logs` to the project command recently.

**Comment by amands98** [comment]
> keep in mind that the harbor CLIs should also be usable in non-interactive mode, In CI/CD pipelines, in scripts. piping in yaml/json and outputting jsons/yaml are equally important.

It will works both ways.

**Comment by amands98** [comment]
added table for project logs -
image

**Pull request merged**
