### PR TITLE
Isolate all the cobra cli commands under `cli` Folder

### PR DESCRIPTION
**Pull request by bishal7679**
# Part of fixing #11

## Previous State
- Previously, cobra CLI commands/flags were bit messed up
- Codebase was unstructured

#### part 1
- [x] Restructured the whole codebase with efficient manner
- [x] Separated all the cobra functions eg. `func CreateProjectCommand() *cobra.Command` to `cli/cmd` folder with `root.go` which is for adding all the cobra cli func with `RootCmd`. This cobra func is using all the `RunFunction`  from `api` folder i.e. `apis.go`

### CODE REVIEW

**Comment by JaeAeich** [comment]
IMO, the code base structure follows the recommended guidelines, especially using the `internal` folder this PR removes.
Maybe some things can be restructured, but I don't think it is needed. 

PS: I don't want to be intrusive, just an opinion.

**Comment by bishal7679** [comment]
> IMO, the code base structure follows the recommended guidelines, especially using the `internal` folder this PR removes. Maybe some things can be restructured, but I don't think it is needed.
> 
> PS: I don't want to be intrusive, just an opinion.

Actually here the main aim is to separate all the jargons cli, api which would be more efficient for any contributor also to understand the codebase easily. And PR #16 adding `internal/pkg` folder which is also signifying all the internal package being utilized!
WDYT?

**Review by amands98 — CHANGES_REQUESTED** [review]
Let's keep the current folder structure; restructuring isn't necessary as effort has already been invested in this [PR](https://github.com/goharbor/harbor-cli/pull/4).

**Comment by bishal7679** [comment]
> Let's keep the current folder structure; restructuring isn't necessary as effort has already been invested in this [PR](https://github.com/goharbor/harbor-cli/pull/4).

Let's wait for @Vad1mo what this PR seems to him as it also took a lot of effort and interrelated with #16 to separte the whole api and cli. Doesn't it make this codebase more enhanced than previous state in order to understand by any new contributor?

**Comment by amands98** [comment]
closing this PR, since it no longer required. // @Vad1mo

**Pull request closed without merging**
