### PR TITLE
Revamping building and release with dagger multibuild pipeline

### PR DESCRIPTION
**Pull request by bishal7679**
# Fixing #22

## Previous State
- Previously, building Makefile based
- releasing with dagger pipeline missing

## Current Behavior
- [x] Added building file as go code with dagger `build.go`
- [x] Automated the release with dagger CI by calling for `release` and `pull_request` event separately [added `deb` `rpm` package based binary release with architecture]
- [x] Added Software Bill of Materials (SBOM) generation during release for each archive by analyzing the various generated artifacts using [Syft](https://github.com/anchore/syft)
- [ ] Added `brew install` support
   - We need to create a separate repo under `goharbor` named `homebrew-tap` for uploading the tap formula which will eventually be used during brew installation

## Screenshot

 

PS:-  should be removed `go.work` & `go.work.sum` file after using the release pipeline once!
//cc @Vad1mo

### CODE REVIEW

**Comment by Vad1mo** [comment]
Awesome! 

I'll looking forward to try this out!

**Comment by bishal7679** [comment]
Hello @Vad1mo @OrlinVasilev 
PTAL in this PR!

**Comment by bishal7679** [comment]
@Vad1mo could you pls take a look on it. Now with dagger CI it's also adding release binary to multiple pkg manager and its workflow files running successfully!

**Comment by Vad1mo** [comment]
build go is building not the harbor cli but rather the build.go file

Something lke this: 
`build = build.WithExec([]string{"go", "build", "-o", path, "/src/cmd/harbor/main.go"})`

**Comment by Vad1mo** [comment]
can you also provide instrustion on how to test ideally locally the release and pull-request flow?

**Comment by bishal7679** [comment]
> can you also provide instrustion on how to test ideally locally the release and pull-request flow?

To test the `release` and `pull-request` flow locally we need to follow the below steps:-
 ### 1. Release
 - Set the environment variable for `GITHUB_TOKEN` like this
   ```bash
    export GITHUB_TOKEN="Your GH token here"
   ```
 - after that make sure to push a new tag beforehand proceeding with release flow
   ```bash
    git tag -a v0.2.0 -m "message here..." && git push origin v0.2.0
   ```
 **NOTE:-** The below command will automatically be triggered whenever a new tag will be pushed 
            to the repo for release
 - Now we are ready to run the release command
   ```go
    go run ci/dagger.go release $GITHUB_TOKEN
   ```


 ### 2. Pull-request
 - Here just run the command with GITHUB_TOKEN set
   ```go
    go run ci/dagger.go pull-request $GITHUB_TOKEN
   ```
 **NOTE:-** This pull-request action flow will be triggered whenever a new pull-request come to this repo. At first it will check whether all test files are passed or not then will create a --snapshot for the current release and will signal for ready-to-merge

I hope this will help!!

**Comment by Vad1mo** [comment]
We need to make sure that this PR replaces the current Makefile.
To do so builder.go should have feature and function parity with the Makefile. 

Also remove in the PR, the Makefile.

**Comment by Vad1mo** [comment]
also update the Readme.md, explainin how to build and test locally

**Comment by Vad1mo** [comment]
The name of the generated SPDX file should have this pattern `harbor_cli_0.2.x.sbom`
There should be only one sbom. It makes things more confusing having two.

**Comment by amands98** [comment]
What is the status here ? :thinking:

**Comment by bishal7679** [comment]
> What is the status here ? 🤔

Currently migrating from using dagger package to dagger module like `dagger call` and was facing some weird error of exporting the build directory from container to host but finally I got it solved today and will soon update a commit to merge!!

**Comment by bupd** [comment]
@bishal7679 please upload screenshots of the features added.

**Comment by bishal7679** [comment]
> @bishal7679 please upload screenshots of the features added.

Now we are able to build harbor cli through dagger call by this command
```bash
dagger call build-harbor --directory-arg . export --path=./
```
But the obstacle for this PR is with the release part. Getting again a weird go version error in go.mod even though its carrying the version with 1.22.5
See the logs here:
https://github.com/bishal7679/harbor-cli/actions/runs/10018821023/job/27694660442#step:4:357

**Review by Vad1mo — APPROVED** [review]

**Comment by bupd** [comment]
@bishal7679 please squash and sign the commits.

**Comment by Vad1mo** [comment]
@bishal7679 please fix DCO and the failing test.  https://github.com/goharbor/harbor-cli/actions/runs/10074141257/job/27969136509?pr=25

**Comment by amands98** [comment]
do you require any help @bishal7679

**Comment by bishal7679** [comment]
Closing as completed by #133

**Pull request closed without merging**
