### PR TITLE
Add: created schedule cmd

### PR DESCRIPTION
**Pull request by Althaf66**
Created new command `schedule` 

`harbor schedule list` - which shows all scheduled jobs in harbor

### CODE REVIEW

**Comment by bupd** [comment]
merge conflicts!

**Comment by Althaf66** [comment]
fixed merge conflicts!

**Comment by Althaf66** [comment]
image

**Comment by Althaf66** [comment]
ready for review

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
