### PR TITLE
feat: Added tests for the `pkg/utils/config.go` file

### PR DESCRIPTION
**Pull request by criticic**
- Adds unit tests for the `pkg/utils/config.go` file
- Improves code coverage of utils package from 0% to ~44%~ 46.4%

Related to #23

### CODE REVIEW

**Comment by criticic** [comment]
@Vad1mo Kindly take a look, and let me know if I should make any changes.

**Comment by criticic** [comment]
Added tests for some more conditions, now the total coverage of utils pkg has improved from 0 to 46.4%

**Review by amands98 — CHANGES_REQUESTED** [review]
Since we've changed a lot of code, can you update the test here?

**Comment by criticic** [comment]
Sure, I'll make the changes

**Pull request closed without merging**
