### PR TITLE
Improving the README.md.

### LINKED ISSUE #55: Improve the readme of Harbor-Cli
Issue -> We need to enhance the readability and descriptive nature of the Harbor-CLI project's readme file.

Note -> take a look at how other projects organize their readme.

### PR DESCRIPTION
**Pull request by muaz-32**
Fixes #55 

Restructured the readme.

### CODE REVIEW

**Review by amands98 — CHANGES_REQUESTED** [review]
Can we add more details around here.
examples -> [1](https://github.com/goharbor/harbor), [2](https://github.com/kubernetes/kubectl)

**Comment by muaz-32** [comment]
> Can we add more details around here. examples -> [1](https://github.com/goharbor/harbor), [2](https://github.com/kubernetes/kubectl)

Should I add the description of Harbor in the Harbor CLI project or refer to the Harbor repo?

**Comment by muaz-32** [comment]
> Hey @muaz-32 You may take a look in this PR #62 ! As it will create conflict of effort, so we can collaborate in one

Sure. I have no problem. @amands98 what's your suggestion?

**Comment by amands98** [comment]
Work together to solve the problem.

**Comment by muaz-32** [comment]
> Work together to solve the problem.

To collaborate in one on which branch of which repo should I make the PR? or where @bishal7679 should make the PR?

**Pull request closed without merging**
