### PR TITLE
Add MAN PAGES Documentation script

### PR DESCRIPTION
**Pull request by bupd**
### Description:
Created script to automate document generation for the cli.
  - This script will generate markdown files for all commands in harbor-cli

### CLI Documentation:
- Documented advanced features and usage scenarios.

### Markdown:
- Incorporated examples and explanations for clarity.
- Ensured consistency with CLI documentation. 

### Below is the example of documentation in **markdown** format for the `harbor project` command.
docGeneration

### Below is the example of documentation in **man** format for the `harbor project` command.
manDoc

### CODE REVIEW

**Review by amands98 — COMMENTED** [review]
Why use two scripts, man_doc.go and md_doc.go, when we could use just one to generate Markdown files.

**Comment by bupd** [comment]
- `man_doc.go` will generate man pages for **Command Line**.
- `md_doc.go` will generate markdown pages for **Web UI**.

**Comment by amands98** [comment]
we need md pages just for web UI

**Comment by bupd** [comment]
> we need md pages just for web UI

Man pages are essential for every CLI tool, right? Are we missing something.

**Comment by Althaf66** [comment]
Disable those "Autogenerated by spf13/cobra" statement.

**Comment by bupd** [comment]
ready for review @Vad1mo

**Comment by bupd** [comment]
@Vad1mo ready to merge!!.

This PR adds script for generating man pages doc.

**Comment by amands98** [comment]
The PR below is better at convincing for docs.

https://github.com/goharbor/harbor-cli/pull/115

**Comment by bupd** [comment]
> The PR below is better at convincing for docs.
> 
> #115

We can use that for md docs for the website.

This PR specifically focuses on Man docs

**Pull request merged**
