### PR TITLE
Validate and Trim Spaces for All User Input Fields

### PR DESCRIPTION
**Pull request by JianMinTang**
Fix all user input fields, such as:

-  harbor login
-  harbor artifact tags create
-  harbor user create
-  harbor project create
-  harbor registry create

this PR fixes the issue #195

### CODE REVIEW

**Comment by JianMinTang** [comment]
ready for review.

**Comment by bupd** [comment]
@JianMinTang Please add trimspace for all input fields. 
which can be done easily by adding the below lines to the validate func
```go
		trimmedStr := strings.TrimSpace(str)
		loginView.Server = trimmedStr
```

also you can take a look at this [Review](https://github.com/goharbor/harbor-cli/pull/66#pullrequestreview-2312492192)

**Comment by bupd** [comment]
Merge Conflicts!!

**Comment by JianMinTang** [comment]
> Merge Conflicts!!

It solved, if only add the below lines to the validate function.
```
trimmedStr := strings.TrimSpace(str)
loginView.Server = trimmedStr
```
The second line of code doesn't work as expected. For example, when you log in using the Harbor CLI and input "demo.goharbor.io " in the terminal, the loginView.Server variable still shows "demo.goharbor.io " without updating.

**Comment by bupd** [comment]
> "demo.goharbor.io " in the terminal, the loginView.Server variable still shows "demo.goharbor.io "
Yes, it's working as deigned. Validate will execute only when you switch to next inputs or press 'Enter'.


So it will validate and update in the background.

**Review by Vad1mo — APPROVED** [review]

**Pull request merged**
